"""BrokerAdapter Protocol（EXECUTION_SPEC §49）。rebalance 不是唯一 primitive。"""

from __future__ import annotations

from typing import Any, Protocol


class BrokerAdapter(Protocol):
    def get_account(self) -> dict[str, Any]: ...

    def get_positions(self) -> dict[str, float]: ...

    def get_cash(self) -> float: ...

    def get_quote(self, symbol: str) -> dict[str, Any]: ...

    def get_instrument(self, symbol: str) -> dict[str, Any]: ...

    def place_order(self, order: Any) -> Any: ...

    def cancel_order(self, order_id: str) -> bool: ...

    def get_order(self, order_id: str) -> dict[str, Any]: ...

    def get_fills(self, order_id: str) -> list[dict[str, Any]]: ...
