from __future__ import annotations

import hashlib
import json
from pathlib import Path

from .config import validate_branch_name, validate_remote_name, validate_repository_locator
from .errors import BridgeError
from .markers import atomic_write_text


def _toml_string(value: str | Path) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def project_key(repo_root: Path) -> str:
    repo = repo_root.resolve()
    digest = hashlib.sha256(str(repo).encode("utf-8")).hexdigest()[:8]
    stem = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in repo.name) or "project"
    return f"{stem}-{digest}"


def default_config_path(repo_root: Path) -> Path:
    return Path.home() / ".webgpt_wake_bridge" / "config" / f"{project_key(repo_root)}.local.toml"


def default_runtime_dir(repo_root: Path) -> Path:
    return Path.home() / ".webgpt_wake_bridge" / "runtime" / project_key(repo_root)


def write_initial_config(
    repo_root: Path,
    *,
    config_path: Path | None = None,
    runtime_dir: Path | None = None,
    remote: str = "origin",
    branch: str = "main",
    marker_root: str = "docs/web_bridge",
    review_repository: str = "",
    cdp_endpoint: str = "http://127.0.0.1:9222",
    chrome_profile_path: str = r"C:\ChatGPT_Automation_Profile",
) -> Path:
    """Create an untracked-by-default local config outside the consumer repo."""
    repo = repo_root.expanduser().resolve()
    if not (repo / ".git").exists():
        raise BridgeError(f"repo is not a Git worktree: {repo}")
    remote = validate_remote_name(remote)
    branch = validate_branch_name(branch)
    routed_repo = validate_repository_locator(review_repository, required=False) or ""

    marker = Path(marker_root)
    if marker.is_absolute() or marker == Path(".") or ".." in marker.parts or marker.parts[:1] == (".git",):
        raise BridgeError("marker_root for init must be a safe repository-relative subdirectory")

    destination = (config_path or default_config_path(repo)).expanduser().resolve()
    runtime = (runtime_dir or default_runtime_dir(repo)).expanduser().resolve()
    if destination.exists():
        raise BridgeError(f"config already exists; refusing overwrite: {destination}")
    if destination == repo or runtime == repo:
        raise BridgeError("config/runtime path must not equal the consumer repository")

    text = f"""# Generated by webgpt-bridge init. Keep this file local and untracked.\n\n[project]\nrepo_root = {_toml_string(repo)}\nremote = {_toml_string(remote)}\nbranch = {_toml_string(branch)}\nmarker_root = {_toml_string(marker.as_posix())}\n\n[review]\n# REQUIRED before `once` or `daemon`; must match the configured GitHub remote.\nrepository = {_toml_string(routed_repo)}\n\n[browser]\ncdp_endpoint = {_toml_string(cdp_endpoint)}\nchrome_profile_path = {_toml_string(chrome_profile_path)}\n# REQUIRED before `noop`, `once`, or `daemon`:\ntarget_conversation_url = \"\"\n\n[runtime]\npoll_interval_s = 5\nfetch_ack_timeout_s = 120\nruntime_dir = {_toml_string(runtime)}\nmax_log_bytes = 1048576\nlog_backups = 3\n"""
    atomic_write_text(destination, text)
    return destination
